<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $fillable = ['votes_count', 'body'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($answer) {
            $answer->question->increment("answers_count");
            $answer->question->save();
        });


        static::saved(function ($answer) {

        });
        static::deleted(function ($answer) {
            $answer->question->decrement("answer_count");
        });

        static::updated(function ($answer) {

        });


    }

    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }

}
